eatout_app/dine_app/urls.py
from django.conf.urls import url
from dine_app import views

app_name = 'restaurant'
urlpatterns = [
    url(r'^search/', views.RestaurantSearchView.as_view(), name="restaurant_search"),
    url(r'^add/', views.AddRestaurantView.as_view(), name="new_restaurant"),
    url(r'^visited/', views.VistedRestaurantsDataView.as_view(), name="visited_restaurants"),
    url(r'^visit/', views.VistedRestaurantsStoreView.as_view(), name="visited_restaurant_save"),
    url(r'^list/', views.RestaurantsListView.as_view(), name="restaurants_list"),
    url(r'^down/', views.VoteDownView.as_view(), name="vote_down"),
    url(r'^display/(?P<slug>.+)/', views.RestaurantDataView.as_view(), name="restaurant_info"),
]

eatout_app/eatout_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from settings import dev

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user_profile.urls')),
    url(r'^restaurant/', include('dine_app.urls')),
    url(r'^api/', include('restaurant_api.urls')),
] + static(dev.MEDIA_URL, document_root=dev.MEDIA_ROOT)

eatout_app/restaurant_api/urls.py
from django.conf.urls import include, url
from restaurant_api import views

app_name = 'api'
urlpatterns = [
    url(r'^search/', views.RestaurantSearchApiView.as_view(), name="restaurant_search"),
    url(r'^add/', views.AddRestaurantApiView.as_view(), name="new_restaurant"),
    url(r'^visited/', views.VistedRestaurantsApiDataView.as_view(), name="visited_restaurants"),
    url(r'^visit/', views.VistedRestaurantsStoreApiView.as_view(), name="visited_restaurant_save"),
    url(r'^list/', views.RestaurantsListApiView.as_view(), name="restaurants_list"),
    url(r'^down/', views.VoteDownApiView.as_view(), name="vote_down"),
    url(r'^display/(?P<slug>.+)/', views.RestaurantDataApiView.as_view(), name="restaurant_info"),
]

eatout_app/user_profile/urls.py
from django.conf.urls import include, url
from user_profile import views

app_name = 'user'

urlpatterns = [
    url(r'^details/', views.UserDetailsView.as_view(), name="user_data"),
]

eatout_app/restaurant_api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
import uuid


class Restaurantdb(models.Model):
    restaurant_id = models.CharField(max_length=225, primary_key=True)
    name = models.CharField(max_length=225, null=False, blank=False)
    geocode = models.CharField(max_length=500, null=True, blank=True)
    address = models.CharField(max_length=225, null=True, blank=True)
    image_url = models.CharField(max_length=525, null=True, blank=True)
    visted = models.IntegerField(default=0)
    user_rated = models.IntegerField(default=1)
    google_rating = models.CharField(max_length=225, null=True, blank=True)
    contact = models.CharField(max_length=13, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return Restaurant Id."""
        return str(self.restaurant_id)


class RestaurantReviews(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    reviews = models.CharField(max_length=3000, null=False, blank=False)
    visted = models.IntegerField(default=0, null=True, blank=True)
    registered_user = models.ForeignKey(User, related_name='reviews', null=True)
    restaurant = models.ForeignKey(Restaurantdb, related_name='reviews', null=True)
    user_rating = models.CharField(max_length=225, null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return review Id."""
        return str(self.id)


class ReviewsComments(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    registered_user = models.ForeignKey(User, related_name='comments', null=True)
    reviews = models.ForeignKey(RestaurantReviews, related_name='comments', null=True)
    comments = models.CharField(max_length=3000)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return comment Id."""
        return str(self.id)


class VisitedRes(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    visted = models.IntegerField(default=0, null=True, blank=True)
    registered_user = models.ForeignKey(User, related_name='visited', null=True)
    restaurant = models.ForeignKey(Restaurantdb, related_name='visited', null=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return  Id."""
        return str(self.id)

eatout_app/dine_app/views.py
"""View for Search Api."""
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

import json

from .serializers import RestaurantSerializer, ReviewsSerializer, CommentsSerializer
from restaurant_api.models import Restaurantdb, VisitedRes
from restaurant import search


class RestaurantSearchView(APIView):
    """Restaurant Search View."""

    renderer_classes = [TemplateHTMLRenderer, JSONRenderer, ]
    template_name = 'restaurant/search.html'

    def get(self, request):
        return Response(status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        coordinates = request.data.get("coordinates")
        query = request.data.get("query")
        if query and coordinates:
            result = search.searchbyquery(query, coordinates)
            return Response(result)
        elif query:
            result = search.searchbyquery(query, coordinates)
            return render(request, 'restaurant/result.html', {"result":
                                                              result['data']})
        elif coordinates:
            result = search.searchbycordinates(coordinates)
            return Response(result)
        else:
            return Response({"data": "no data send"})


class AddRestaurantView(APIView):
    """Add a new restautrant from search result to our database."""

    def post(self, request, *args, **kwargs):
        data = request.data
        if Restaurantdb.objects.filter(restaurant_id=data["restaurant_id"]).exists():
            return HttpResponse("Restaurant already added")
        else:
            res_data = RestaurantSerializer(data=data)
            if res_data.is_valid():
                res_data.save()
                return HttpResponseRedirect(reverse("restaurant:restaurants_list"))


class VistedRestaurantsDataView(APIView):
    """List out all the Restaurant visited by the user."""
    renderer_classes = [TemplateHTMLRenderer, ]
    template_name = 'restaurant/visited.html'

    def get(self, request):
        # Displaying only restaurants marked visited by users
        data = Restaurantdb.objects.filter(visted__gt=0, user_rated__gt=0)
        if data:
            res_data = serializers.serialize("json", data)
            restaurants = {"restaurants": json.loads(res_data)}
            return Response(restaurants, status=status.HTTP_200_OK)
        else:
            return Response(restaurants, status=status.HTTP_200_OK)


class RestaurantsListView(APIView):
    """Display all the restaurant added into database by user."""

    renderer_classes = [TemplateHTMLRenderer, ]
    template_name = 'restaurant/list.html'

    def get(self, request):
        # user is able check all the restaurants
        res_data = serializers.serialize("json", Restaurantdb.objects.all())
        restaurants = {"restaurants": json.loads(res_data)}
        return Response(restaurants, status=status.HTTP_200_OK)


class RestaurantDataView(LoginRequiredMixin, APIView):
    """Api outputs all the data about the restaurant stored in database."""

    renderer_classes = [TemplateHTMLRenderer, ]
    template_name = 'restaurant/place_display.html'

    def get(self, request, slug):
        restaurant = Restaurantdb.objects.get(restaurant_id=slug)
        data = {"restaurant": restaurant}
        return Response(data, status=status.HTTP_200_OK)

    def post(self, request, slug):
        # stores user reviews and comments
        data = request.data.copy()
        data["registered_user"] = request.user.pk
        if "comments" in data:
            rev_data = CommentsSerializer(data=data)
            if rev_data.is_valid():
                rev_data.save()
                return HttpResponseRedirect(reverse("restaurant:restaurant_info", args=[slug]))
        else:
            data["restaurant"] = slug
            rev_data = ReviewsSerializer(data=data)
            if rev_data.is_valid():
                rev_data.save()
                return HttpResponseRedirect(reverse("restaurant:restaurant_info", args=[slug]))


class VistedRestaurantsStoreView(LoginRequiredMixin, APIView):
    """Record the user response of visiting the restaurant."""

    renderer_classes = [TemplateHTMLRenderer, ]
    template_name = 'restaurant/visited.html'

    def post(self, request):
        res_data = Restaurantdb.objects.get(
            restaurant_id=request.data.get("r_id"))
        data = VisitedRes.objects.get_or_create(
            registered_user=request.user, restaurant=res_data, defaults={"visted": 1})
        res_data.visted = res_data.visted + 1
        res_data.save()
        if not data[1]:
            data[0].visted = data[0].visted + 1
            data[0].save()
        return HttpResponseRedirect(reverse("restaurant:restaurant_info", args=[request.data.get("r_id")]))


class VoteDownView(LoginRequiredMixin, APIView):
    """Voting down the restaurant resulting user will not find the restaurants
    again in the list."""

    def post(self, request):
        res_data = Restaurantdb.objects.get(
            restaurant_id=request.data.get("r_id"))
        res_data.user_rated = 0
        res_data.save()
        return HttpResponseRedirect(reverse("restaurant:restaurant_info", args=[request.data.get("r_id")]))

eatout_app/restaurant_api/views.py
"""View for Search Api."""
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.core import serializers

import json

from .serializers import RestaurantSerializer, ReviewsSerializer, CommentsSerializer
from .models import Restaurantdb, VisitedRes
from restaurant import search


class RestaurantSearchApiView(APIView):
    """Restaurant Search Api."""

    def post(self, request, *args, **kwargs):
        coordinates = request.data.get("coordinates")
        query = request.data.get("query")
        if query and coordinates:
            result = search.searchbyquery(query, coordinates)
            return Response(result)
        elif query:
            result = search.searchbyquery(query, coordinates)
            return Response(result)
        elif coordinates:
            result = search.searchbycordinates(coordinates)
            return Response(result)
        else:
            return Response({"data": "no data send"})


class AddRestaurantApiView(APIView):
    """Api to  add a new restautrant to our database."""

    def post(self, request, *args, **kwargs):
        data = request.data
        if Restaurantdb.objects.filter(restaurant_id=data["restaurant_id"]).exists():
            return Response({"Response": "Restaurant already added"})
        else:
            res_data = RestaurantSerializer(data=data)
            if res_data.is_valid():
                res_data.save()
                return Response(res_data)


class VistedRestaurantsApiDataView(APIView):
    """List out all the Restaurant visited by the user Api."""

    def get(self, request):
        data = Restaurantdb.objects.filter(visted__gt=0, user_rated__gt=0)
        if data:
            res_data = serializers.serialize("json", data)
            restaurants = {"restaurants": json.loads(res_data)}
            return Response(restaurants, status=status.HTTP_200_OK)
        else:
            return Response(restaurants, status=status.HTTP_200_OK)


class RestaurantsListApiView(APIView):
    """Api to display all the restaurant added into database by user."""

    def get(self, request):
        res_data = serializers.serialize(
            "json", Restaurantdb.objects.filter(user_rated__gt=0))
        restaurants = {"restaurants": json.loads(res_data)}
        return Response(restaurants, status=status.HTTP_200_OK)


class RestaurantDataApiView(APIView):
    """Api outputs all the data about the restaurant stored in database."""

    authentication_classes = [TokenAuthentication, ]
    permission_classes = [IsAuthenticated, ]

    def get(self, request, slug):
        res_data = serializers.serialize(
            "json", Restaurantdb.objects.filter(restaurant_id=slug))
        data = {"restaurant": json.loads(res_data)}
        return Response(data, status=status.HTTP_200_OK)

    def post(self, request, slug):
        # stores user reviews and comments
        data = request.data.copy()
        data["registered_user"] = request.user.pk
        if "comments" in data:
            rev_data = CommentsSerializer(data=data)
            if rev_data.is_valid():
                rev_data.save()
                return Response(data, status=status.HTTP_200_OK)
        else:
            data["restaurant"] = slug
            rev_data = ReviewsSerializer(data=data)
            if rev_data.is_valid():
                rev_data.save()
                return Response(data, status=status.HTTP_200_OK)


class VistedRestaurantsStoreApiView(APIView):
    """Record the user feedback of visiting the restaurant."""

    authentication_classes = [TokenAuthentication, ]
    permission_classes = [IsAuthenticated, ]

    def post(self, request):
        res_data = Restaurantdb.objects.get(
            restaurant_id=request.data.get("restaurant_id"))
        data = VisitedRes.objects.get_or_create(
            registered_user=request.user, restaurant=res_data,
            defaults={"visted": 1})
        res_data.visted = res_data.visted + 1
        res_data.save()
        if not data[1]:
            data[0].visted = data[0].visted + 1
            data[0].save()
            res_data = serializers.serialize(
                "json", [data[0]])
        return Response(json.loads(res_data))


class VoteDownApiView(APIView):
    """Voting down the restaurant resulting user will not find the restaurants
    again in the list."""
    authentication_classes = [TokenAuthentication, ]
    permission_classes = [IsAuthenticated, ]

    def post(self, request):
        res_data = Restaurantdb.objects.get(
            restaurant_id=request.data.get("r_id"))
        res_data.user_rated = 0
        res_data.save()
        res_data = serializers.serialize(
            "json", res_data)
        return Response(json.loads(res_data))

eatout_app/search_api/views.py
"""View for Search Api."""
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from restaurant import search


class RestaurantSearchApiView(APIView):
    """Restaurant Search Api."""
    renderer_classes = (JSONRenderer, )

    def post(self, request, *args, **kwargs):

        coordinates = request.data.get("coordinates")
        query = request.data.get("query")
        if query and coordinates:
            result = search.searchbyquery(query, coordinates)
            return Response(result)
        elif query:
            result = search.searchbyquery(query, coordinates)
            return Response(result)
        elif coordinates:
            result = search.searchbycordinates(coordinates)
            return Response(result)
        else:
            return Response({"data": "no data send"})

eatout_app/user_profile/views.py
"""View for UserProfile."""
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserDetail


class UserDetailsView(LoginRequiredMixin, APIView):
    """Restaurant Search Api."""
    renderer_classes = [TemplateHTMLRenderer, JSONRenderer, ]
    template_name = 'userprofile/user_data.html'

    def get(self, request):
        user = UserDetail.objects.get(user=request.user)
        data = {"user": user}
        return Response(data, status=status.HTTP_200_OK)

eatout_app/eatout_app/templates/restaurant/list.html
{% load static from staticfiles %} {% load i18n %} {% load account %} {% load json_extra %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Restaurants | Eat Out</title>
    <!-- CORE CSS-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
    <style type="text/css">
    html,
    body {
        height: 100%;
    }

    html {
        display: table;
        margin: auto;
    }

    body {
        display: table-cell;
        vertical-align: middle;
        width: 80%;
    }

    .margin {
        margin: 0 !important;
    }
    .row .col.s12 {
    width: 60%;
    margin-left: 0;
    }

    .col.s12>.btn {
        width: 100%;
    }
    p.grey-text.text-darken-4.margin {
    font-size: 25px;
    }
     #map {
        height: 300px;
        width: 30%;
       }
    </style>

</head>

<body>
<div>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'restaurant:restaurant_search'%}">Eat Out</a>
        <a class="navbar-brand" href="{% url 'restaurant:restaurants_list'%}">Restaurants </a>
    <a class="navbar-brand" href="{% url 'restaurant:visited_restaurants'%}">Visited </a>
  </div>
    <div class="navbar-collapse collapse navbar-warning-collapse"><ul class="nav navbar-nav navbar-right">
      
      {% if request.user.is_authenticated %}
      <li><a href="{% url 'user:user_data'%}">{{request.user.username}}</a></li>
                        <li><a href="{% url 'account_logout'%}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login'%}">Sigin</a></li>
                        {% endif %}
    </ul></div>
</div>
    {%for restaurant in restaurants%}
    {%ifequal restaurant.fields.user_rated 1 %}
    <div id="profile-page-wall-posts" class="row">
        <div class="col s12">
            <!-- medium -->
            <div id="profile-page-wall-post" class="card">
                <div class="card-profile-title">
                    <div class="row">
                        <div class="col s1">
                            <img src="{{ restaurant.fields.image_url }}" alt="" class="square responsive-img valign profile-post-uer-image">
                        </div>
                        <div class="col s5">
                            <a href="#"><p class="grey-text text-darken-4 margin">{{ restaurant.fields.name }}</p></a>
                            <span class="grey-text text-darken-1 ultra-small">Address: {{ restaurant.fields.address }}</span>
                        </div>
                        <div class="col s5 right-align">
                            Google Rating: {{ restaurant.fields.google_rating }}
                            <form action="{% url 'restaurant:visited_restaurant_save' %}" method="POST">
                            {% csrf_token %}
                            <button class="btn waves-effect waves-light" type="submit" name="store">Visited</button>
                            <input type="text" name="r_id" value="{{restaurant.pk}}" hidden />
                        </form>
                        </div>
                    </div>
            </div>
            </div>
            </div>
            </div>{% endifequal %}{% endfor %}
            </div>
            <div style="height: 100%; width: 20%; position: absolute; top: 0px; right: 0px; background-color: rgb(229, 227, 223);" id="map"></div>
<!-- ================================================
  Scripts
================================================ -->
            <!-- jQuery Library -->
    <script>

      function initMap() {

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: {lat: 28.5800065, lng: 77.3177433}
        });

        // Create an array of alphabetical characters used to label the markers.
        var labels = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

        // Add some markers to the map.
        // Note: The code uses the JavaScript Array.prototype.map() method to
        // create an array of markers based on a given "locations" array.
        // The map() method here has nothing to do with the Google Maps API.
        var markers = [];
        i=0
        {%for restaurant in restaurants%}
        if ({{restaurant.fields.user_rated}} > 0) {
           var geo = JSON.parse({{restaurant.fields.geocode|to_json}});
           console.log(geo.lat);
           var lt=parseFloat(geo.lat)
           var ln=parseFloat(geo.lon)

        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(lt, ln),
            label: labels[i % labels.length]
        });
        markers.push(marker);
        i=i+1
    }
        {% endfor %}

        // Add a marker clusterer to manage the markers.
        var markerCluster = new MarkerClusterer(map, markers,
            {imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m'});
      }
    </script>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXo2p1vXYi6UQ9Wp0pW_iLEKBC5a345yo&callback=initMap">
</script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!--materialize js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
</body>

</html>

eatout_app/eatout_app/templates/restaurant/place_display.html
{% load static from staticfiles %} {% load i18n %} {% load account %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ restaurant.name }} | Eat Out</title>
    <!-- CORE CSS-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
    <style type="text/css">
    html,
    body {
        height: 100%;
    }

    html {
        display: table;
        margin: auto;
    }

    body {
        display: table-cell;
        vertical-align: middle;
        width: 80%;
    }

    .margin {
        margin: 0 !important;
    }

    .col.s12>.btn {
        width: 100%;
    }

    p.grey-text.text-darken-4.margin {
        font-size: 30px;
    }

    #map {
        height: 300px;
        width: 30%;
    }
    </style>
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'restaurant:restaurant_search'%}">Eat Out</a>
    <a class="navbar-brand" href="{% url 'restaurant:restaurants_list'%}">Restaurants </a>
    <a class="navbar-brand" href="{% url 'restaurant:visited_restaurants'%}">Visited </a>
  </div>
  <div class="navbar-collapse collapse navbar-warning-collapse"><ul class="nav navbar-nav navbar-right">
      
      {% if request.user.is_authenticated %}
      <li><a href="{% url 'user:user_data'%}">{{request.user.username}}</a></li>
                        <li><a href="{% url 'account_logout'%}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login'%}">Sigin</a></li>
                        {% endif %}
    </ul></div>
</div>
    <!-- medium -->
    <div id="profile-page-wall-post" class="card" style="margin-top: 50px;">
        <div class="card-profile-title">
            <div class="row">
                <div class="col s1">
                    <img src="{{ restaurant.image_url }}" alt="" class="square responsive-img valign profile-post-uer-image">
                </div>
                <div class="col s2 right-align">
                    <p class="grey-text text-darken-4 margin">{{ restaurant.name }}</p>
                    <span class="grey-text text-darken-1 ultra-small">Address: {{ restaurant.address }}</span>
                </div>
                <!--<div class="col s1" id="map"></div>-->
                <div class="col s7 right-align">
                    Google Rating: {{ restaurant.google_rating }}
                    
                <form action="{% url 'restaurant:vote_down' %}" method="POST">
                {% csrf_token %}
                <h3><a href="#" onclick="$(this).closest('form').submit()"><i class="mdi-action-thumb-down"></i></a></h3>
                <input type="text" name="r_id" value="{{restaurant.pk}}" hidden />
            </form>
                <form action="{% url 'restaurant:visited_restaurant_save' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit" name="store">Visited</button>
                <input type="text" name="r_id" value="{{restaurant.pk}}" hidden />
            </form>
                </div>
            </div>
        </div>
    </div>
    <div id="profile-page-wall-post" class="card">
        <div class="card-action row">
            <form action="." method="POST">
                {% csrf_token %}
                <input type="text" name="reviews" placeholder="new review" />
                <button class="btn btn-primary" type="submit" name="store">New review</button>
            </form>
        </div>
    </div>
    <div id="profile-page-wall-post" class="card">
        <div class="card-action row">
            <h4>Reviews</h4>
            {%for review in restaurant.reviews.all %}
            <div><h5>{{ review.reviews }}</h5></p><p style="margin-left: 70px; color:#189643">{{ review.registered_user }}{% ifequal request.user.username review.registered_user.username %}<i class="mdi-action-star-rate"></i>{% endifequal%}</p></div>
            <div id="comments"> 
    <details>
        <summary>
               Comments
        </summary>
                {%for comment in review.comments.all %}
                <div class="content">
            <p>
        {{ comment.comments }}</p><p style="margin-left: 70px; color:#ee6e73">{{ comment.registered_user }}{% ifequal request.user.username comment.registered_user.username %}<i class="mdi-action-star-rate"></i>{% endifequal%}</p>
        </div>
                {%endfor%}</details>
                <form action="." method="POST">
                    {% csrf_token %}
                    <input type="text" name="comments" placeholder="new comment" />
                    <input type="text" name="reviews" value="{{review.id}}" hidden />
                    <button class="btn btn-primary" type="submit" name="store">New comment</button>
                </form>
            </div>
            {% endfor %}

    </div>
    </div>
    <!-- ================================================
  Scripts
================================================ -->
    <!-- jQuery Library -->
    <script>
    var cor = "{{ restaurant.geocode }}"
    var la = cor.split(",")

    function initMap() {
        var uluru = { lat: parseFloat(la[0]), lng: parseFloat(la[1]) };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 16,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXo2p1vXYi6UQ9Wp0pW_iLEKBC5a345yo&callback=initMap">
    </script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!--materialize js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
</body>

</html>